''''''
"""
There are 3 Types of Error. 
LOGICAL , SYNTAX & RUN TIME Errors.

Logical Error: A mistake in a program's source code that results in an incorrect or unexpected behavior.

Syntax Error: A syntax error occurs when a programmer writes an invalid statement. such as spelling and punctuation 
                errors, incorrect labels, and so on, which cause an error message to be generated by the compiler.
 
Run-time  Error: A runtime error is a type of error that occurs during program execution. The Python interpreter  
                    executes a script if it is syntactically correct. However, if it encounters an issue at runtime,
                    which is not detected when the script is parsed, script execution may halt unexpectedly.
"""

''' 
Logical errors – also called semantic errors, logical errors cause the program to behave incorrectly, but they do not
                 usually crash the program. Unlike a program with syntax errors, a program with logic errors can be run, 
                 but it does not operate as intended.
'''

''' Example of those Error '''

''' Syntax Error: Unterminated String Literal'''
# print("Let's get some Error Example.)


''' Syntax Error: unmatched'''
# a = 2
# b = 4
# if (a > b):
#     print('a- Big')
# else:
#     print("b- Big")


''' runtime Error: '''
# print(3/0)


''' Semantic Error: unexpected output, Wrong Logic '''
# a = 20
# b = 10
# print(a+b/3)


''' Type Error: '''
#
# a = 10
# b = "20"
# print(a+b)


''' Name Error: '''
# a = 10
# rslt = a +b
# print(rslt)


''' Value Error:'''
# a = "Hello"
# print(int(a))


''' Indentation Error '''
# a = "Hello"
#     print(a)


''' list index Error '''
# a = [1,2,3,4,5]
# print(a[5])
